Update v_people.staff_roster.sql
TEAMSchools/gabby pull request #294
Opened 2021-11-18 16:29 UTC by kevinverhoff

Adding in the new custom fields

Building out race/ethnicity tagging for Native American/First Nation

**Code checks:**
1) Is your branch up to date with `main`? Update from `main` and resolve and merge conflicts before submitting.
2) Are you `JOIN`-ing to a subquery? Refactor as a `CTE`.
3) Do your CTEs significantly transform the data, or could they be refactored into simple `JOIN`s?
4) Will every `SELECT` column be used downstream? Remove superfluous columns.
5) Does every table `JOIN` introduce columns that are used downstream? Remove superfluous `JOIN`s.
6) Double check that your SQL conforms to the style guide.
   * All tables should be referenced in three-parts: `{database}.{schema}.{table}`
   * All columns sould be prefixed with a table alias: `t.column_name`
   * All keywords should be UPPERCASE; all identifiers should be `snake_case`
   * In the event an identifier shares a name with a keyword, surround it with [square brackets].
   * Spaces, not tabs.
    
**What is the purpose of this view?**
> *[extract|feed|clean-up|other] Brief explanation...*

2021-11-18 18:32 UTC, cbini requested changes
these new columns are custom fields right? we should add them from the custom fields view and not `employees`

2021-11-29 18:48 UTC, kevinverhoff commented
okay - this is ready to go now. I updated the source for the custom fields and tweaked some of the logic around race/ethnicity

2021-11-30 21:00 UTC, cbini commented
blocked by #295

2021-12-01 21:02 UTC, cbini approved these changes

2021-12-01 21:02 UTC, merged