Race/Ethnicity & Gender Updates
TEAMSchools/gabby pull request #299
Opened 2021-12-08 18:46 UTC by kevinverhoff

-Reworking race/ethnicity grouping logic on staff roster
-Adding in gender
-Adding gender to attrition
-Adding race/ethnicity & gender to S&O survey details

**Code checks:**
1) Is your branch up to date with `main`? Update from `main` and resolve and merge conflicts before submitting.
2) Are you `JOIN`-ing to a subquery? Refactor as a `CTE`.
3) Do your CTEs significantly transform the data, or could they be refactored into simple `JOIN`s?
4) Will every `SELECT` column be used downstream? Remove superfluous columns.
5) Does every table `JOIN` introduce columns that are used downstream? Remove superfluous `JOIN`s.
6) Double check that your SQL conforms to the style guide.
   * All tables should be referenced in three-parts: `{database}.{schema}.{table}`
   * All columns sould be prefixed with a table alias: `t.column_name`
   * All keywords should be UPPERCASE; all identifiers should be `snake_case`
   * In the event an identifier shares a name with a keyword, surround it with [square brackets].
   * Spaces, not tabs.
    
**What is the purpose of this view?**
> *[extract|feed|clean-up|other] Brief explanation...*

2021-12-09 17:08 UTC, cbini requested changes

2021-12-09 17:10 UTC, cbini commented on people/v_people.staff_roster.sql
> +       JOIN gabby.adp.employees e
just checked, it's on there

2021-12-09 19:22 UTC, kevinverhoff commented
@cbini Alright I think we're good now!

2021-12-10 16:35 UTC, cbini approved these changes

2021-12-10 16:35 UTC, merged