Dayforce removal
TEAMSchools/gabby pull request #301
Opened 2021-12-08 21:27 UTC by cristinabaldor

Replacing references to dayforce tables with adp, for v_surveys.cmo_engagement_regional_survey_detail.sql @kevinverhoff added ethnicity columns

**Code checks:**
1) Is your branch up to date with `main`? Update from `main` and resolve and merge conflicts before submitting.
2) Are you `JOIN`-ing to a subquery? Refactor as a `CTE`.
3) Do your CTEs significantly transform the data, or could they be refactored into simple `JOIN`s?
4) Will every `SELECT` column be used downstream? Remove superfluous columns.
5) Does every table `JOIN` introduce columns that are used downstream? Remove superfluous `JOIN`s.
6) Double check that your SQL conforms to the style guide.
   * All tables should be referenced in three-parts: `{database}.{schema}.{table}`
   * All columns sould be prefixed with a table alias: `t.column_name`
   * All keywords should be UPPERCASE; all identifiers should be `snake_case`
   * In the event an identifier shares a name with a keyword, surround it with [square brackets].
   * Spaces, not tabs.
    
**What is the purpose of this view?**
> *[extract|feed|clean-up|other] Brief explanation...*

2021-12-09 17:03 UTC, cbini requested changes

2021-12-09 17:03 UTC, cbini commented on surveys/v_surveys.manager_survey_detail.sql
> + AND w.is_current_record = 1
`is_current_record` could contradict the date join, you want to use only one or the other

2021-12-09 17:03 UTC, cbini commented on surveys/v_surveys.manager_survey_detail.sql
> + AND w.is_current_record = 1
ditto

2021-12-13 19:07 UTC, kevinverhoff commented
@cbini we just updated these together. Because we're launching the engagement survey this week, would it be possible to merge this before Wednesday? (upping to hotfix)

2021-12-13 20:13 UTC, cbini approved these changes

2021-12-13 20:13 UTC, merged